trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: default
  steps:
  - checkout: self
  - task: NodeTool@0
    displayName: Use Node 14.x
    inputs:
      versionSpec: 14.x
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: NET6AngularSeed
      verbose: false
  - task: Npm@1
    displayName: npm custom
    inputs:
      command: custom
      workingDir: NET6AngularSeed
      verbose: false
      customCommand: run prod
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: '**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
  - task: DeleteFiles@1
    displayName: Delete files from $(Build.SourcesDirectory)
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: '*'